### ISSUE TITLE
Published docker image

### ISSUE THREAD

**Issue by jkburges** [buildkite/terminal-to-html#102]
Is there a reason that there's no official docker image for this tool? That would make it easy to use on the Elastic CI stack. Otherwise, what's the recommended way for making terminal-to-html available to jobs on the Elastic CI stack?

**Comment by triarius** [comment]
Hi @jkburges, thanks for your interest in this tool. Usually, this is something we use internally to render the logs for a job on buildkite.com. We don't typically see people use on the Elastic CI stack, so we're curious what your use case for it is. Please let us know.

Having said that, you should be able to download the binary from the release page with commands such as:

```bash
curl -sSL https://github.com/buildkite/terminal-to-html/releases/download/v3.7.0/terminal-to-html-3.7.0-linux-amd64.gz > terminal-to-html.gz | gunzip > terminal-to-html
chmod +x terminal-to-html
termanal-to-html --version
```
And then use it in your steps.

**Comment by jkburges** [comment]
> We don't typically see people use on the Elastic CI stack, so we're curious what your use case for it is. Please let us know.

We use, it along with a couple of other utils, for adding terraform summaries (of what's planned to change) to the top of our builds, e.g.:

```
 PLAN_SUMMARY=`terraform show -json tfplan | tf-summarize | terminal-to-html`

  cat << EOF | buildkite-agent annotate --style "warning" --append --context "ctx-warn-$TERRAFORM_ENVIRONMENT"
  <details><summary class="h3">Summary</summary>
    <code><pre class="term">${PLAN_SUMMARY}</pre></code>
  </details>
```

> you should be able to download the binary from the release page with commands such as

ok, thanks.

**Comment by triarius** [comment]
> We use, it along with a couple of other utils, for adding terraform summaries (of what's planned to change) to the top of our builds, e.g.:

Very cool, that sound really useful! Thanks for letting us know
