### ISSUE TITLE
[Feature request] Add an option to customize title of output HTML

### ISSUE THREAD

**Issue by tddschn** [buildkite/terminal-to-html#148]
Thanks for making this wonderful tool!

I wish it has an option to customize title of output HTML, would you consider implementing that?

**Comment by DrJosh9000** [comment]
Hi @tddschn, thanks for the request. Could you elaborate a bit? Are you thinking of:

- a flag that controls the `<title>` included when using `-preview`?
- support for OSCs that change the window title? e.g. `ESC ]0;new title BEL`
- changing the title of something on buildkite.com?
