### ISSUE TITLE
Rename repo to terminal-to-html ?

### ISSUE THREAD

**Issue by paul-hammant** [buildkite/terminal-to-html#52]
why? better googleability for one.

* Github handles redirects from old name just fine.
* Github routes push/pull from/to old remote namses just fine

**Comment by lox** [comment]
This makes sense to me!

**Comment by lox** [comment]
Would mean `go get` installs the right binary name too.

**Comment by toolmantim** [comment]
Let's do it!

**Comment by lox** [comment]
Done!

**Comment by toolmantim** [comment]
We'll need to redirect http://buildkite.github.io/terminal/ because it seems GitHub doesn't do that automatically, and we link to it from the docs (which I'm updating anyhow, but it's good if we can redirect) 🤔

**Comment by toolmantim** [comment]
I just added a redirect in the best way you can, given GitHub Pages limitations: https://github.com/buildkite/buildkite.github.io/commit/9e1920390ccbe810a79def808ff5bfaed1528137
