### ISSUE TITLE
avoid mangling curly quotes

### ISSUE THREAD

**Issue by ljharb** [buildkite/terminal-to-html#53]
My command line tool values proper typography, and so it uses curly quotes (`“ ” ‘ ’`) whenever appropriate ;-)

However, this causes output in the build log like `���foo���` when I expect `“foo”`. Can that be fixed?

**Comment by ticky** [comment]
Hey @ljharb, terminal-to-html should understand unicode just fine, so this sounds like a weird one. If you want to shoot [support](https://buildkite.com/support) an email with a link to a build that’s showing this, we can dig into what’s gone wrong!

**Comment by ljharb** [comment]
Sure, email sent! I'd have posted the build here, but it's internal.

**Comment by ticky** [comment]
It looks like this was resolved in support, and was an issue with another component and not `terminal-to-html`!
