### ISSUE TITLE
No changelog or binaries for 3.2.0 release

### ISSUE THREAD

**Issue by huonw** [buildkite/terminal-to-html#63]
https://github.com/buildkite/terminal-to-html/releases/tag/v3.2.0 seems to just be the git tag at the moment, not a changelog with attached binaries like https://github.com/buildkite/terminal-to-html/releases/tag/v3.1.0.

**Comment by sj26** [comment]
Sorry about that! There was only one tiny change (#56) which was to work around random control characters generated by Docker buildkit output. I've just written some notes and attached binaries here:

https://github.com/buildkite/terminal-to-html/releases/tag/v3.2.0
