### ISSUE TITLE
v3.3.0 Not Go Module Compatible

### ISSUE THREAD

**Issue by donatj** [buildkite/terminal-to-html#74]
The v3.3.0 release added a `go.mod` and `go.sum` but isn't properly versioned so it cannot be used with Go Modules.

Go has a good writeup about how you need to specially handle versions 2 and greater here:

https://blog.golang.org/v2-go-modules

**Comment by donatj** [comment]
This appears fixed? Is it fixed? lol

**Comment by yob** [comment]
oops, [thanks for pointing this out](https://donatstudios.com/Go-v2-Modules).

It's fixed on master, but we haven't tagged a new release so downstream users are still having a bad time (see  #77)

**Comment by yob** [comment]
I've published a [v.3.4.0 release](https://github.com/buildkite/terminal-to-html/releases/tag/v3.4.0), which I believe fixes this issue.

I haven't retrospectively changed the earlier 3.x releases that are unusable when go modules are enabled - mutating the tags felt icky and ultimately not really necessary. 

Thanks again for highlighting this!
