### ISSUE TITLE
Add support to install with homebrew

### ISSUE THREAD

**Issue by AdamCoulterOz** [buildkite/terminal-to-html#85]
would love this available using

`brew install terminal-to-html`

would support updates to the compiled binaries for darwin using `brew upgrade` along with all my other dev tools.
could do the same thing for windows using `chocolatey` and linux using `apt`

**Comment by ticky** [comment]
This is now available in our [`homebrew-buildkite` tap](https://github.com/buildkite/homebrew-buildkite); you can install via `brew install buildkite/buildkite/terminal-to-html`
